version: '3'
services:
 cdh5-in-docker:
        build: . 
        image: hadoop/cdh5       
        ports:
         - "8020:8020"
         - "50070:50070"
         - "50010:50010"
         - "50020:50020"
         - "50075:50075"
         - "8030:8030"
         - "8031:8031"
         - "8032:8032"
         - "8033:8033"
         - "8088:8088"
         - "8040:8040"
         - "8042:8042"
         - "10020:10020"
         - "19888:19888"
         - "8888:8888"
         - "18080:18080"
         - "9999:9999"
         - "10000:10000"
        volumes:
          - ./data:/data
          - ./scripts:/scripts
        entrypoint: [ "/bin/bash" ]
        privileged: true
        tty: true
