#!/bin/bash

## initialize zookeeper
service zookeeper-server start

## initialize HDFS
service hadoop-hdfs-datanode start
service hadoop-hdfs-namenode start
service hadoop-hdfs-journalnode start
service hadoop-hdfs-secondarynamenode start

## setup hdfs folders before starting other components

su - hdfs -c "hadoop fs -mkdir -p /user/hdfs"
su - hdfs -c "hadoop fs -chown hdfs /user/hdfs"
su - hdfs -c "hadoop fs -mkdir /user/spark"
su - hdfs -c "hadoop fs -mkdir /user/spark/applicationHistory"
su - hdfs -c "hadoop fs -chown -R spark:spark /user/spark"
su - hdfs -c "hadoop fs -chmod 1777 /user/spark/applicationHistory"
su - hdfs -c "hadoop fs -mkdir -p /tmp/hadoop-yarn/staging/history/done_intermediate"
su - hdfs -c "hadoop fs -chown -R mapred:mapred /tmp/hadoop-yarn/staging"
su - hdfs -c "hadoop fs -chmod -R 1777 /tmp"
su - hdfs -c "hadoop fs -mkdir -p /var/log/hadoop-yarn"
su - hdfs -c "hadoop fs -chown yarn:mapred /var/log/hadoop-yarn"
su - spark -c "hadoop fs -mkdir -p /user/spark/share/lib"
su - spark -c "hadoop fs -put /usr/lib/spark/lib/spark-assembly.jar /user/spark/share/lib/spark-assembly.jar"

## start yarn and mapreduce
service hadoop-httpfs start
service hadoop-mapreduce-historyserver start
service hadoop-yarn-nodemanager start
service hadoop-yarn-resourcemanager start
service spark-history-server start
##service hue start
service hive-metastore start
service hive-server2 start
